import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="content-grid ">
   <Header />


      
        {children}
        </main>
        </body>
    </html>
  )
}
